apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  namespace: kafka-prod
  labels:
    strimzi.io/cluster: kafka-cluster # kafka cluster's name
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi # Production Recommended 100Gi
        kraftMetadata: shared
        deleteClaim: false
